server:
  port: 8000

token:
  secret: 4d516a02898d2166e5aec5d66037f196d4317ffa175a2b737e0fb535ecd9fcc6

spring:
  application:
    name: Gateway-Client
  cloud:
    gateway:
#      default-filters:
#        - name: GlobalFilter #Global Filter로 지정된 java 파일 이름
#          args:
#            baseMessage: Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true
      routes:
        - id: show_tc_dstrct_mng
#          uri: lb://show-tcDstrctMng-service
          uri:
            http://localhost:8081
          predicates:
            - Path=/service1/**
            - name: Method
              args:
                methods:
                  -  GET
          filters:
            - name: JwtAuthenticationFilterFactory
              args:
                preLogger: true
                postLogger: true
        - id: show_tl_mvmneq_pass
          uri: http://localhost:8082
          predicates:
            - Path=/service2/**
            - name: Method
              args:
                methods:
                  - GET
          filters:
            - name: JwtAuthenticationFilterFactory
              args:
                preLogger: true
                postLogger: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka


